peft_model:
  id: dvquy13/fin-falcon-7b-lora:0.0.1
model:
  id: tiiuae/falcon-7b-instruct
  template_name: "falcon"
  max_new_tokens: 500
  temperature: 1.0
setup:
  device: cuda:0
  debug: True
dataset:
  file: "testing_data.json"